//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMoto.ViewModels
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnouncementForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class AnnouncementForView : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string BodyTypeNameField;
        
        private string BrandNameField;
        
        private string ColorNameField;
        
        private string DescriptionField;
        
        private int IdAnnouncementField;
        
        private System.Nullable<int> MileageField;
        
        private string ModelNameField;
        
        private bool NegotiableField;
        
        private System.Nullable<int> PowerField;
        
        private int PriceField;
        
        private System.Nullable<int> ProDateField;
        
        private System.Nullable<int> StrokeCapacityField;
        
        private string TitleField;
        
        private string UserNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyTypeName
        {
            get
            {
                return this.BodyTypeNameField;
            }
            set
            {
                this.BodyTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName
        {
            get
            {
                return this.BrandNameField;
            }
            set
            {
                this.BrandNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName
        {
            get
            {
                return this.ColorNameField;
            }
            set
            {
                this.ColorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnnouncement
        {
            get
            {
                return this.IdAnnouncementField;
            }
            set
            {
                this.IdAnnouncementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Mileage
        {
            get
            {
                return this.MileageField;
            }
            set
            {
                this.MileageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName
        {
            get
            {
                return this.ModelNameField;
            }
            set
            {
                this.ModelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Negotiable
        {
            get
            {
                return this.NegotiableField;
            }
            set
            {
                this.NegotiableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Power
        {
            get
            {
                return this.PowerField;
            }
            set
            {
                this.PowerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProDate
        {
            get
            {
                return this.ProDateField;
            }
            set
            {
                this.ProDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StrokeCapacity
        {
            get
            {
                return this.StrokeCapacityField;
            }
            set
            {
                this.StrokeCapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMotoService")]
public interface IMotoService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnouncements", ReplyAction="http://tempuri.org/IMotoService/GetAnnouncementsResponse")]
    WcfMoto.ViewModels.AnnouncementForView[] GetAnnouncements();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnouncements", ReplyAction="http://tempuri.org/IMotoService/GetAnnouncementsResponse")]
    System.Threading.Tasks.Task<WcfMoto.ViewModels.AnnouncementForView[]> GetAnnouncementsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnoucementSortByTitle", ReplyAction="http://tempuri.org/IMotoService/GetAnnoucementSortByTitleResponse")]
    WcfMoto.ViewModels.AnnouncementForView[] GetAnnoucementSortByTitle();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnoucementSortByTitle", ReplyAction="http://tempuri.org/IMotoService/GetAnnoucementSortByTitleResponse")]
    System.Threading.Tasks.Task<WcfMoto.ViewModels.AnnouncementForView[]> GetAnnoucementSortByTitleAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMotoServiceChannel : IMotoService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MotoServiceClient : System.ServiceModel.ClientBase<IMotoService>, IMotoService
{
    
    public MotoServiceClient()
    {
    }
    
    public MotoServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MotoServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MotoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MotoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public WcfMoto.ViewModels.AnnouncementForView[] GetAnnouncements()
    {
        return base.Channel.GetAnnouncements();
    }
    
    public System.Threading.Tasks.Task<WcfMoto.ViewModels.AnnouncementForView[]> GetAnnouncementsAsync()
    {
        return base.Channel.GetAnnouncementsAsync();
    }
    
    public WcfMoto.ViewModels.AnnouncementForView[] GetAnnoucementSortByTitle()
    {
        return base.Channel.GetAnnoucementSortByTitle();
    }
    
    public System.Threading.Tasks.Task<WcfMoto.ViewModels.AnnouncementForView[]> GetAnnoucementSortByTitleAsync()
    {
        return base.Channel.GetAnnoucementSortByTitleAsync();
    }
}
