//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//
//     Zmiany w tym pliku mogą spowodować niewłaściwe zachowanie i zostaną utracone
//     w przypadku ponownego wygenerowania kodu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceMoto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnouncementForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class AnnouncementForView : object
    {
        
        private string BodyTypeNameField;
        
        private string BrandNameField;
        
        private string ColorNameField;
        
        private string DescriptionField;
        
        private int IdAnnouncementField;
        
        private System.Nullable<int> MileageField;
        
        private string ModelNameField;
        
        private bool NegotiableField;
        
        private System.Nullable<int> PowerField;
        
        private int PriceField;
        
        private System.Nullable<int> ProDateField;
        
        private System.Nullable<int> StrokeCapacityField;
        
        private string TitleField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyTypeName
        {
            get
            {
                return this.BodyTypeNameField;
            }
            set
            {
                this.BodyTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName
        {
            get
            {
                return this.BrandNameField;
            }
            set
            {
                this.BrandNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName
        {
            get
            {
                return this.ColorNameField;
            }
            set
            {
                this.ColorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnnouncement
        {
            get
            {
                return this.IdAnnouncementField;
            }
            set
            {
                this.IdAnnouncementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Mileage
        {
            get
            {
                return this.MileageField;
            }
            set
            {
                this.MileageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName
        {
            get
            {
                return this.ModelNameField;
            }
            set
            {
                this.ModelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Negotiable
        {
            get
            {
                return this.NegotiableField;
            }
            set
            {
                this.NegotiableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Power
        {
            get
            {
                return this.PowerField;
            }
            set
            {
                this.PowerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProDate
        {
            get
            {
                return this.ProDateField;
            }
            set
            {
                this.ProDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StrokeCapacity
        {
            get
            {
                return this.StrokeCapacityField;
            }
            set
            {
                this.StrokeCapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMoto.IMotoService")]
    public interface IMotoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnouncements", ReplyAction="http://tempuri.org/IMotoService/GetAnnouncementsResponse")]
        ServiceReferenceMoto.GetAnnouncementsResponse GetAnnouncements(ServiceReferenceMoto.GetAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnouncements", ReplyAction="http://tempuri.org/IMotoService/GetAnnouncementsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnouncementsResponse> GetAnnouncementsAsync(ServiceReferenceMoto.GetAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnoucementSortByTitle", ReplyAction="http://tempuri.org/IMotoService/GetAnnoucementSortByTitleResponse")]
        ServiceReferenceMoto.GetAnnoucementSortByTitleResponse GetAnnoucementSortByTitle(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnoucementSortByTitle", ReplyAction="http://tempuri.org/IMotoService/GetAnnoucementSortByTitleResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnoucementSortByTitleResponse> GetAnnoucementSortByTitleAsync(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnouncements", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnouncementsRequest
    {
        
        public GetAnnouncementsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnouncementsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnouncementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnouncementsResult;
        
        public GetAnnouncementsResponse()
        {
        }
        
        public GetAnnouncementsResponse(System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnouncementsResult)
        {
            this.GetAnnouncementsResult = GetAnnouncementsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnoucementSortByTitle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnoucementSortByTitleRequest
    {
        
        public GetAnnoucementSortByTitleRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnoucementSortByTitleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnoucementSortByTitleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnoucementSortByTitleResult;
        
        public GetAnnoucementSortByTitleResponse()
        {
        }
        
        public GetAnnoucementSortByTitleResponse(System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnoucementSortByTitleResult)
        {
            this.GetAnnoucementSortByTitleResult = GetAnnoucementSortByTitleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IMotoServiceChannel : ServiceReferenceMoto.IMotoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MotoServiceClient : System.ServiceModel.ClientBase<ServiceReferenceMoto.IMotoService>, ServiceReferenceMoto.IMotoService
    {
        
        /// <summary>
        /// Wdróż tę metodę częściową, aby skonfigurować punkt końcowy usługi.
        /// </summary>
        /// <param name="serviceEndpoint">Punkt końcowy do skonfigurowania</param>
        /// <param name="clientCredentials">Poświadczenia klienta</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MotoServiceClient() : 
                base(MotoServiceClient.GetDefaultBinding(), MotoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMotoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), MotoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReferenceMoto.GetAnnouncementsResponse GetAnnouncements(ServiceReferenceMoto.GetAnnouncementsRequest request)
        {
            return base.Channel.GetAnnouncements(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnouncementsResponse> GetAnnouncementsAsync(ServiceReferenceMoto.GetAnnouncementsRequest request)
        {
            return base.Channel.GetAnnouncementsAsync(request);
        }
        
        public ServiceReferenceMoto.GetAnnoucementSortByTitleResponse GetAnnoucementSortByTitle(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request)
        {
            return base.Channel.GetAnnoucementSortByTitle(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnoucementSortByTitleResponse> GetAnnoucementSortByTitleAsync(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request)
        {
            return base.Channel.GetAnnoucementSortByTitleAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMotoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMotoService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64946/MotoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Nie można znaleźć punktu końcowego o nazwie „{0}”.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MotoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMotoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MotoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMotoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMotoService,
        }
    }
}
