//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceMoto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnouncementForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class AnnouncementForView : object
    {
        
        private string BodyTypeNameField;
        
        private string BrandNameField;
        
        private string ColorNameField;
        
        private string DescriptionField;
        
        private int IdAnnouncementField;
        
        private System.Nullable<int> MileageField;
        
        private string ModelNameField;
        
        private bool NegotiableField;
        
        private System.Nullable<int> PowerField;
        
        private int PriceField;
        
        private System.Nullable<int> ProDateField;
        
        private System.Nullable<int> StrokeCapacityField;
        
        private string TitleField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyTypeName
        {
            get
            {
                return this.BodyTypeNameField;
            }
            set
            {
                this.BodyTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName
        {
            get
            {
                return this.BrandNameField;
            }
            set
            {
                this.BrandNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName
        {
            get
            {
                return this.ColorNameField;
            }
            set
            {
                this.ColorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnnouncement
        {
            get
            {
                return this.IdAnnouncementField;
            }
            set
            {
                this.IdAnnouncementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Mileage
        {
            get
            {
                return this.MileageField;
            }
            set
            {
                this.MileageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName
        {
            get
            {
                return this.ModelNameField;
            }
            set
            {
                this.ModelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Negotiable
        {
            get
            {
                return this.NegotiableField;
            }
            set
            {
                this.NegotiableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Power
        {
            get
            {
                return this.PowerField;
            }
            set
            {
                this.PowerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProDate
        {
            get
            {
                return this.ProDateField;
            }
            set
            {
                this.ProDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StrokeCapacity
        {
            get
            {
                return this.StrokeCapacityField;
            }
            set
            {
                this.StrokeCapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class UserForView : object
    {
        
        private int IdUserField;
        
        private bool IsActiveField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser
        {
            get
            {
                return this.IdUserField;
            }
            set
            {
                this.IdUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMoto.IMotoService")]
    public interface IMotoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnouncements", ReplyAction="http://tempuri.org/IMotoService/GetAnnouncementsResponse")]
        ServiceReferenceMoto.GetAnnouncementsResponse GetAnnouncements(ServiceReferenceMoto.GetAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnouncements", ReplyAction="http://tempuri.org/IMotoService/GetAnnouncementsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnouncementsResponse> GetAnnouncementsAsync(ServiceReferenceMoto.GetAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddOrUpdateAnnouncements", ReplyAction="http://tempuri.org/IMotoService/AddOrUpdateAnnouncementsResponse")]
        ServiceReferenceMoto.AddOrUpdateAnnouncementsResponse AddOrUpdateAnnouncements(ServiceReferenceMoto.AddOrUpdateAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddOrUpdateAnnouncements", ReplyAction="http://tempuri.org/IMotoService/AddOrUpdateAnnouncementsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.AddOrUpdateAnnouncementsResponse> AddOrUpdateAnnouncementsAsync(ServiceReferenceMoto.AddOrUpdateAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnoucementSortByTitle", ReplyAction="http://tempuri.org/IMotoService/GetAnnoucementSortByTitleResponse")]
        ServiceReferenceMoto.GetAnnoucementSortByTitleResponse GetAnnoucementSortByTitle(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnoucementSortByTitle", ReplyAction="http://tempuri.org/IMotoService/GetAnnoucementSortByTitleResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnoucementSortByTitleResponse> GetAnnoucementSortByTitleAsync(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUsers", ReplyAction="http://tempuri.org/IMotoService/GetUsersResponse")]
        ServiceReferenceMoto.GetUsersResponse GetUsers(ServiceReferenceMoto.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUsers", ReplyAction="http://tempuri.org/IMotoService/GetUsersResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetUsersResponse> GetUsersAsync(ServiceReferenceMoto.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUsersSortByUsername", ReplyAction="http://tempuri.org/IMotoService/GetUsersSortByUsernameResponse")]
        ServiceReferenceMoto.GetUsersSortByUsernameResponse GetUsersSortByUsername(ServiceReferenceMoto.GetUsersSortByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUsersSortByUsername", ReplyAction="http://tempuri.org/IMotoService/GetUsersSortByUsernameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetUsersSortByUsernameResponse> GetUsersSortByUsernameAsync(ServiceReferenceMoto.GetUsersSortByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddOrUpdateUser", ReplyAction="http://tempuri.org/IMotoService/AddOrUpdateUserResponse")]
        ServiceReferenceMoto.AddOrUpdateUserResponse AddOrUpdateUser(ServiceReferenceMoto.AddOrUpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddOrUpdateUser", ReplyAction="http://tempuri.org/IMotoService/AddOrUpdateUserResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.AddOrUpdateUserResponse> AddOrUpdateUserAsync(ServiceReferenceMoto.AddOrUpdateUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnouncements", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnouncementsRequest
    {
        
        public GetAnnouncementsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnouncementsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnouncementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnouncementsResult;
        
        public GetAnnouncementsResponse()
        {
        }
        
        public GetAnnouncementsResponse(System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnouncementsResult)
        {
            this.GetAnnouncementsResult = GetAnnouncementsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateAnnouncements", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateAnnouncementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceMoto.AnnouncementForView announcement;
        
        public AddOrUpdateAnnouncementsRequest()
        {
        }
        
        public AddOrUpdateAnnouncementsRequest(ServiceReferenceMoto.AnnouncementForView announcement)
        {
            this.announcement = announcement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateAnnouncementsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateAnnouncementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateAnnouncementsResult;
        
        public AddOrUpdateAnnouncementsResponse()
        {
        }
        
        public AddOrUpdateAnnouncementsResponse(bool AddOrUpdateAnnouncementsResult)
        {
            this.AddOrUpdateAnnouncementsResult = AddOrUpdateAnnouncementsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnoucementSortByTitle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnoucementSortByTitleRequest
    {
        
        public GetAnnoucementSortByTitleRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnoucementSortByTitleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnoucementSortByTitleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnoucementSortByTitleResult;
        
        public GetAnnoucementSortByTitleResponse()
        {
        }
        
        public GetAnnoucementSortByTitleResponse(System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnoucementSortByTitleResult)
        {
            this.GetAnnoucementSortByTitleResult = GetAnnoucementSortByTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersRequest
    {
        
        public GetUsersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.UserForView> GetUsersResult;
        
        public GetUsersResponse()
        {
        }
        
        public GetUsersResponse(System.Collections.Generic.List<ServiceReferenceMoto.UserForView> GetUsersResult)
        {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersSortByUsername", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersSortByUsernameRequest
    {
        
        public GetUsersSortByUsernameRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersSortByUsernameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersSortByUsernameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.UserForView> GetUsersSortByUsernameResult;
        
        public GetUsersSortByUsernameResponse()
        {
        }
        
        public GetUsersSortByUsernameResponse(System.Collections.Generic.List<ServiceReferenceMoto.UserForView> GetUsersSortByUsernameResult)
        {
            this.GetUsersSortByUsernameResult = GetUsersSortByUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceMoto.UserForView User;
        
        public AddOrUpdateUserRequest()
        {
        }
        
        public AddOrUpdateUserRequest(ServiceReferenceMoto.UserForView User)
        {
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateUserResult;
        
        public AddOrUpdateUserResponse()
        {
        }
        
        public AddOrUpdateUserResponse(bool AddOrUpdateUserResult)
        {
            this.AddOrUpdateUserResult = AddOrUpdateUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IMotoServiceChannel : ServiceReferenceMoto.IMotoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MotoServiceClient : System.ServiceModel.ClientBase<ServiceReferenceMoto.IMotoService>, ServiceReferenceMoto.IMotoService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MotoServiceClient() : 
                base(MotoServiceClient.GetDefaultBinding(), MotoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMotoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), MotoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReferenceMoto.GetAnnouncementsResponse GetAnnouncements(ServiceReferenceMoto.GetAnnouncementsRequest request)
        {
            return base.Channel.GetAnnouncements(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnouncementsResponse> GetAnnouncementsAsync(ServiceReferenceMoto.GetAnnouncementsRequest request)
        {
            return base.Channel.GetAnnouncementsAsync(request);
        }
        
        public ServiceReferenceMoto.AddOrUpdateAnnouncementsResponse AddOrUpdateAnnouncements(ServiceReferenceMoto.AddOrUpdateAnnouncementsRequest request)
        {
            return base.Channel.AddOrUpdateAnnouncements(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.AddOrUpdateAnnouncementsResponse> AddOrUpdateAnnouncementsAsync(ServiceReferenceMoto.AddOrUpdateAnnouncementsRequest request)
        {
            return base.Channel.AddOrUpdateAnnouncementsAsync(request);
        }
        
        public ServiceReferenceMoto.GetAnnoucementSortByTitleResponse GetAnnoucementSortByTitle(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request)
        {
            return base.Channel.GetAnnoucementSortByTitle(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnoucementSortByTitleResponse> GetAnnoucementSortByTitleAsync(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request)
        {
            return base.Channel.GetAnnoucementSortByTitleAsync(request);
        }
        
        public ServiceReferenceMoto.GetUsersResponse GetUsers(ServiceReferenceMoto.GetUsersRequest request)
        {
            return base.Channel.GetUsers(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetUsersResponse> GetUsersAsync(ServiceReferenceMoto.GetUsersRequest request)
        {
            return base.Channel.GetUsersAsync(request);
        }
        
        public ServiceReferenceMoto.GetUsersSortByUsernameResponse GetUsersSortByUsername(ServiceReferenceMoto.GetUsersSortByUsernameRequest request)
        {
            return base.Channel.GetUsersSortByUsername(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetUsersSortByUsernameResponse> GetUsersSortByUsernameAsync(ServiceReferenceMoto.GetUsersSortByUsernameRequest request)
        {
            return base.Channel.GetUsersSortByUsernameAsync(request);
        }
        
        public ServiceReferenceMoto.AddOrUpdateUserResponse AddOrUpdateUser(ServiceReferenceMoto.AddOrUpdateUserRequest request)
        {
            return base.Channel.AddOrUpdateUser(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.AddOrUpdateUserResponse> AddOrUpdateUserAsync(ServiceReferenceMoto.AddOrUpdateUserRequest request)
        {
            return base.Channel.AddOrUpdateUserAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMotoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMotoService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64946/MotoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MotoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMotoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MotoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMotoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMotoService,
        }
    }
}
