//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceMoto
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AnnouncementForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class AnnouncementForView : object
    {
        
        private string BodyTypeNameField;
        
        private string BrandNameField;
        
        private string ColorNameField;
        
        private string DescriptionField;
        
        private int IdAnnouncementField;
        
        private int IdUserField;
        
        private bool IsActiveField;
        
        private System.Nullable<int> MileageField;
        
        private string ModelNameField;
        
        private bool NegotiableField;
        
        private System.Nullable<int> PowerField;
        
        private int PriceField;
        
        private System.Nullable<int> ProDateField;
        
        private System.Nullable<int> StrokeCapacityField;
        
        private string TitleField;
        
        private string UserNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BodyTypeName
        {
            get
            {
                return this.BodyTypeNameField;
            }
            set
            {
                this.BodyTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BrandName
        {
            get
            {
                return this.BrandNameField;
            }
            set
            {
                this.BrandNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ColorName
        {
            get
            {
                return this.ColorNameField;
            }
            set
            {
                this.ColorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnnouncement
        {
            get
            {
                return this.IdAnnouncementField;
            }
            set
            {
                this.IdAnnouncementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser
        {
            get
            {
                return this.IdUserField;
            }
            set
            {
                this.IdUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Mileage
        {
            get
            {
                return this.MileageField;
            }
            set
            {
                this.MileageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ModelName
        {
            get
            {
                return this.ModelNameField;
            }
            set
            {
                this.ModelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Negotiable
        {
            get
            {
                return this.NegotiableField;
            }
            set
            {
                this.NegotiableField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Power
        {
            get
            {
                return this.PowerField;
            }
            set
            {
                this.PowerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ProDate
        {
            get
            {
                return this.ProDateField;
            }
            set
            {
                this.ProDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StrokeCapacity
        {
            get
            {
                return this.StrokeCapacityField;
            }
            set
            {
                this.StrokeCapacityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName
        {
            get
            {
                return this.UserNameField;
            }
            set
            {
                this.UserNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class UserForView : object
    {
        
        private int IdUserField;
        
        private bool IsActiveField;
        
        private string PasswordField;
        
        private string UsernameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser
        {
            get
            {
                return this.IdUserField;
            }
            set
            {
                this.IdUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BillForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class BillForView : object
    {
        
        private string AnnouncementTitleField;
        
        private System.DateTime DateToField;
        
        private decimal FinalValueField;
        
        private int IdAnnouncementField;
        
        private int IdBillField;
        
        private int IdServiceField;
        
        private int IdUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnnouncementTitle
        {
            get
            {
                return this.AnnouncementTitleField;
            }
            set
            {
                this.AnnouncementTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTo
        {
            get
            {
                return this.DateToField;
            }
            set
            {
                this.DateToField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FinalValue
        {
            get
            {
                return this.FinalValueField;
            }
            set
            {
                this.FinalValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnnouncement
        {
            get
            {
                return this.IdAnnouncementField;
            }
            set
            {
                this.IdAnnouncementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBill
        {
            get
            {
                return this.IdBillField;
            }
            set
            {
                this.IdBillField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdService
        {
            get
            {
                return this.IdServiceField;
            }
            set
            {
                this.IdServiceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser
        {
            get
            {
                return this.IdUserField;
            }
            set
            {
                this.IdUserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class MessageForView : object
    {
        
        private string AnnouncementTitleField;
        
        private System.DateTime DateField;
        
        private bool FromUserField;
        
        private int IdAnnouncementField;
        
        private int IdAnnouncementUserField;
        
        private int IdMessageField;
        
        private int IdUserField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AnnouncementTitle
        {
            get
            {
                return this.AnnouncementTitleField;
            }
            set
            {
                this.AnnouncementTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FromUser
        {
            get
            {
                return this.FromUserField;
            }
            set
            {
                this.FromUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnnouncement
        {
            get
            {
                return this.IdAnnouncementField;
            }
            set
            {
                this.IdAnnouncementField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAnnouncementUser
        {
            get
            {
                return this.IdAnnouncementUserField;
            }
            set
            {
                this.IdAnnouncementUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdMessage
        {
            get
            {
                return this.IdMessageField;
            }
            set
            {
                this.IdMessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUser
        {
            get
            {
                return this.IdUserField;
            }
            set
            {
                this.IdUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrandForView", Namespace="http://schemas.datacontract.org/2004/07/WcfMoto.ViewModels")]
    public partial class BrandForView : object
    {
        
        private int IdBrandField;
        
        private bool IsActiveField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBrand
        {
            get
            {
                return this.IdBrandField;
            }
            set
            {
                this.IdBrandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceMoto.IMotoService")]
    public interface IMotoService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnouncements", ReplyAction="http://tempuri.org/IMotoService/GetAnnouncementsResponse")]
        ServiceReferenceMoto.GetAnnouncementsResponse GetAnnouncements(ServiceReferenceMoto.GetAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnouncements", ReplyAction="http://tempuri.org/IMotoService/GetAnnouncementsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnouncementsResponse> GetAnnouncementsAsync(ServiceReferenceMoto.GetAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddOrUpdateAnnouncements", ReplyAction="http://tempuri.org/IMotoService/AddOrUpdateAnnouncementsResponse")]
        ServiceReferenceMoto.AddOrUpdateAnnouncementsResponse AddOrUpdateAnnouncements(ServiceReferenceMoto.AddOrUpdateAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddOrUpdateAnnouncements", ReplyAction="http://tempuri.org/IMotoService/AddOrUpdateAnnouncementsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.AddOrUpdateAnnouncementsResponse> AddOrUpdateAnnouncementsAsync(ServiceReferenceMoto.AddOrUpdateAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnoucementSortByTitle", ReplyAction="http://tempuri.org/IMotoService/GetAnnoucementSortByTitleResponse")]
        ServiceReferenceMoto.GetAnnoucementSortByTitleResponse GetAnnoucementSortByTitle(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetAnnoucementSortByTitle", ReplyAction="http://tempuri.org/IMotoService/GetAnnoucementSortByTitleResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnoucementSortByTitleResponse> GetAnnoucementSortByTitleAsync(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUsers", ReplyAction="http://tempuri.org/IMotoService/GetUsersResponse")]
        ServiceReferenceMoto.GetUsersResponse GetUsers(ServiceReferenceMoto.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUsers", ReplyAction="http://tempuri.org/IMotoService/GetUsersResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetUsersResponse> GetUsersAsync(ServiceReferenceMoto.GetUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUsersSortByUsername", ReplyAction="http://tempuri.org/IMotoService/GetUsersSortByUsernameResponse")]
        ServiceReferenceMoto.GetUsersSortByUsernameResponse GetUsersSortByUsername(ServiceReferenceMoto.GetUsersSortByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUsersSortByUsername", ReplyAction="http://tempuri.org/IMotoService/GetUsersSortByUsernameResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetUsersSortByUsernameResponse> GetUsersSortByUsernameAsync(ServiceReferenceMoto.GetUsersSortByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddOrUpdateUser", ReplyAction="http://tempuri.org/IMotoService/AddOrUpdateUserResponse")]
        ServiceReferenceMoto.AddOrUpdateUserResponse AddOrUpdateUser(ServiceReferenceMoto.AddOrUpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddOrUpdateUser", ReplyAction="http://tempuri.org/IMotoService/AddOrUpdateUserResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.AddOrUpdateUserResponse> AddOrUpdateUserAsync(ServiceReferenceMoto.AddOrUpdateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetBills", ReplyAction="http://tempuri.org/IMotoService/GetBillsResponse")]
        ServiceReferenceMoto.GetBillsResponse GetBills(ServiceReferenceMoto.GetBillsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetBills", ReplyAction="http://tempuri.org/IMotoService/GetBillsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetBillsResponse> GetBillsAsync(ServiceReferenceMoto.GetBillsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUserBills", ReplyAction="http://tempuri.org/IMotoService/GetUserBillsResponse")]
        ServiceReferenceMoto.GetUserBillsResponse GetUserBills(ServiceReferenceMoto.GetUserBillsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUserBills", ReplyAction="http://tempuri.org/IMotoService/GetUserBillsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetUserBillsResponse> GetUserBillsAsync(ServiceReferenceMoto.GetUserBillsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUserMessages", ReplyAction="http://tempuri.org/IMotoService/GetUserMessagesResponse")]
        ServiceReferenceMoto.GetUserMessagesResponse GetUserMessages(ServiceReferenceMoto.GetUserMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUserMessages", ReplyAction="http://tempuri.org/IMotoService/GetUserMessagesResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetUserMessagesResponse> GetUserMessagesAsync(ServiceReferenceMoto.GetUserMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUserInAnnouncementMessages", ReplyAction="http://tempuri.org/IMotoService/GetUserInAnnouncementMessagesResponse")]
        ServiceReferenceMoto.GetUserInAnnouncementMessagesResponse GetUserInAnnouncementMessages(ServiceReferenceMoto.GetUserInAnnouncementMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetUserInAnnouncementMessages", ReplyAction="http://tempuri.org/IMotoService/GetUserInAnnouncementMessagesResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetUserInAnnouncementMessagesResponse> GetUserInAnnouncementMessagesAsync(ServiceReferenceMoto.GetUserInAnnouncementMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetBrands", ReplyAction="http://tempuri.org/IMotoService/GetBrandsResponse")]
        ServiceReferenceMoto.GetBrandsResponse GetBrands(ServiceReferenceMoto.GetBrandsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/GetBrands", ReplyAction="http://tempuri.org/IMotoService/GetBrandsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.GetBrandsResponse> GetBrandsAsync(ServiceReferenceMoto.GetBrandsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddAnnouncements", ReplyAction="http://tempuri.org/IMotoService/AddAnnouncementsResponse")]
        ServiceReferenceMoto.AddAnnouncementsResponse AddAnnouncements(ServiceReferenceMoto.AddAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddAnnouncements", ReplyAction="http://tempuri.org/IMotoService/AddAnnouncementsResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.AddAnnouncementsResponse> AddAnnouncementsAsync(ServiceReferenceMoto.AddAnnouncementsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddBill", ReplyAction="http://tempuri.org/IMotoService/AddBillResponse")]
        ServiceReferenceMoto.AddBillResponse AddBill(ServiceReferenceMoto.AddBillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddBill", ReplyAction="http://tempuri.org/IMotoService/AddBillResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.AddBillResponse> AddBillAsync(ServiceReferenceMoto.AddBillRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddMsg", ReplyAction="http://tempuri.org/IMotoService/AddMsgResponse")]
        ServiceReferenceMoto.AddMsgResponse AddMsg(ServiceReferenceMoto.AddMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotoService/AddMsg", ReplyAction="http://tempuri.org/IMotoService/AddMsgResponse")]
        System.Threading.Tasks.Task<ServiceReferenceMoto.AddMsgResponse> AddMsgAsync(ServiceReferenceMoto.AddMsgRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnouncements", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnouncementsRequest
    {
        
        public GetAnnouncementsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnouncementsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnouncementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnouncementsResult;
        
        public GetAnnouncementsResponse()
        {
        }
        
        public GetAnnouncementsResponse(System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnouncementsResult)
        {
            this.GetAnnouncementsResult = GetAnnouncementsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateAnnouncements", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateAnnouncementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceMoto.AnnouncementForView announcement;
        
        public AddOrUpdateAnnouncementsRequest()
        {
        }
        
        public AddOrUpdateAnnouncementsRequest(ServiceReferenceMoto.AnnouncementForView announcement)
        {
            this.announcement = announcement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateAnnouncementsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateAnnouncementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateAnnouncementsResult;
        
        public AddOrUpdateAnnouncementsResponse()
        {
        }
        
        public AddOrUpdateAnnouncementsResponse(bool AddOrUpdateAnnouncementsResult)
        {
            this.AddOrUpdateAnnouncementsResult = AddOrUpdateAnnouncementsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnoucementSortByTitle", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnoucementSortByTitleRequest
    {
        
        public GetAnnoucementSortByTitleRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAnnoucementSortByTitleResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAnnoucementSortByTitleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnoucementSortByTitleResult;
        
        public GetAnnoucementSortByTitleResponse()
        {
        }
        
        public GetAnnoucementSortByTitleResponse(System.Collections.Generic.List<ServiceReferenceMoto.AnnouncementForView> GetAnnoucementSortByTitleResult)
        {
            this.GetAnnoucementSortByTitleResult = GetAnnoucementSortByTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsers", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersRequest
    {
        
        public GetUsersRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.UserForView> GetUsersResult;
        
        public GetUsersResponse()
        {
        }
        
        public GetUsersResponse(System.Collections.Generic.List<ServiceReferenceMoto.UserForView> GetUsersResult)
        {
            this.GetUsersResult = GetUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersSortByUsername", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersSortByUsernameRequest
    {
        
        public GetUsersSortByUsernameRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUsersSortByUsernameResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUsersSortByUsernameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.UserForView> GetUsersSortByUsernameResult;
        
        public GetUsersSortByUsernameResponse()
        {
        }
        
        public GetUsersSortByUsernameResponse(System.Collections.Generic.List<ServiceReferenceMoto.UserForView> GetUsersSortByUsernameResult)
        {
            this.GetUsersSortByUsernameResult = GetUsersSortByUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceMoto.UserForView User;
        
        public AddOrUpdateUserRequest()
        {
        }
        
        public AddOrUpdateUserRequest(ServiceReferenceMoto.UserForView User)
        {
            this.User = User;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddOrUpdateUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddOrUpdateUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddOrUpdateUserResult;
        
        public AddOrUpdateUserResponse()
        {
        }
        
        public AddOrUpdateUserResponse(bool AddOrUpdateUserResult)
        {
            this.AddOrUpdateUserResult = AddOrUpdateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBills", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBillsRequest
    {
        
        public GetBillsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBillsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBillsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.BillForView> GetBillsResult;
        
        public GetBillsResponse()
        {
        }
        
        public GetBillsResponse(System.Collections.Generic.List<ServiceReferenceMoto.BillForView> GetBillsResult)
        {
            this.GetBillsResult = GetBillsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserBills", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserBillsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetUserBillsRequest()
        {
        }
        
        public GetUserBillsRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserBillsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserBillsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.BillForView> GetUserBillsResult;
        
        public GetUserBillsResponse()
        {
        }
        
        public GetUserBillsResponse(System.Collections.Generic.List<ServiceReferenceMoto.BillForView> GetUserBillsResult)
        {
            this.GetUserBillsResult = GetUserBillsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserMessages", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int id;
        
        public GetUserMessagesRequest()
        {
        }
        
        public GetUserMessagesRequest(int id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserMessagesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.MessageForView> GetUserMessagesResult;
        
        public GetUserMessagesResponse()
        {
        }
        
        public GetUserMessagesResponse(System.Collections.Generic.List<ServiceReferenceMoto.MessageForView> GetUserMessagesResult)
        {
            this.GetUserMessagesResult = GetUserMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInAnnouncementMessages", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserInAnnouncementMessagesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int iduser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idannouncement;
        
        public GetUserInAnnouncementMessagesRequest()
        {
        }
        
        public GetUserInAnnouncementMessagesRequest(int iduser, int idannouncement)
        {
            this.iduser = iduser;
            this.idannouncement = idannouncement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUserInAnnouncementMessagesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUserInAnnouncementMessagesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.MessageForView> GetUserInAnnouncementMessagesResult;
        
        public GetUserInAnnouncementMessagesResponse()
        {
        }
        
        public GetUserInAnnouncementMessagesResponse(System.Collections.Generic.List<ServiceReferenceMoto.MessageForView> GetUserInAnnouncementMessagesResult)
        {
            this.GetUserInAnnouncementMessagesResult = GetUserInAnnouncementMessagesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBrands", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBrandsRequest
    {
        
        public GetBrandsRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetBrandsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetBrandsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceMoto.BrandForView> GetBrandsResult;
        
        public GetBrandsResponse()
        {
        }
        
        public GetBrandsResponse(System.Collections.Generic.List<ServiceReferenceMoto.BrandForView> GetBrandsResult)
        {
            this.GetBrandsResult = GetBrandsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddAnnouncements", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddAnnouncementsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int iduser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idbrand;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int idmodel;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public int bodytype;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public int color;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string title;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string des;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int price;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public bool neg;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=9)]
        public int prodate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=10)]
        public int mileage;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=11)]
        public int stcap;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=12)]
        public int power;
        
        public AddAnnouncementsRequest()
        {
        }
        
        public AddAnnouncementsRequest(int iduser, int idbrand, int idmodel, int bodytype, int color, string title, string des, int price, bool neg, int prodate, int mileage, int stcap, int power)
        {
            this.iduser = iduser;
            this.idbrand = idbrand;
            this.idmodel = idmodel;
            this.bodytype = bodytype;
            this.color = color;
            this.title = title;
            this.des = des;
            this.price = price;
            this.neg = neg;
            this.prodate = prodate;
            this.mileage = mileage;
            this.stcap = stcap;
            this.power = power;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddAnnouncementsResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddAnnouncementsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddAnnouncementsResult;
        
        public AddAnnouncementsResponse()
        {
        }
        
        public AddAnnouncementsResponse(bool AddAnnouncementsResult)
        {
            this.AddAnnouncementsResult = AddAnnouncementsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBill", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddBillRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idservice;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idanno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public int iduser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public decimal finalv;
        
        public AddBillRequest()
        {
        }
        
        public AddBillRequest(int idservice, int idanno, int iduser, decimal finalv)
        {
            this.idservice = idservice;
            this.idanno = idanno;
            this.iduser = iduser;
            this.finalv = finalv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddBillResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddBillResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddBillResult;
        
        public AddBillResponse()
        {
        }
        
        public AddBillResponse(bool AddBillResult)
        {
            this.AddBillResult = AddBillResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddMsg", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddMsgRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idanno;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int iduser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public bool fromuser;
        
        public AddMsgRequest()
        {
        }
        
        public AddMsgRequest(int idanno, int iduser, string message, bool fromuser)
        {
            this.idanno = idanno;
            this.iduser = iduser;
            this.message = message;
            this.fromuser = fromuser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddMsgResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddMsgResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AddMsgResult;
        
        public AddMsgResponse()
        {
        }
        
        public AddMsgResponse(bool AddMsgResult)
        {
            this.AddMsgResult = AddMsgResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IMotoServiceChannel : ServiceReferenceMoto.IMotoService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class MotoServiceClient : System.ServiceModel.ClientBase<ServiceReferenceMoto.IMotoService>, ServiceReferenceMoto.IMotoService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MotoServiceClient() : 
                base(MotoServiceClient.GetDefaultBinding(), MotoServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMotoService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), MotoServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MotoServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReferenceMoto.GetAnnouncementsResponse GetAnnouncements(ServiceReferenceMoto.GetAnnouncementsRequest request)
        {
            return base.Channel.GetAnnouncements(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnouncementsResponse> GetAnnouncementsAsync(ServiceReferenceMoto.GetAnnouncementsRequest request)
        {
            return base.Channel.GetAnnouncementsAsync(request);
        }
        
        public ServiceReferenceMoto.AddOrUpdateAnnouncementsResponse AddOrUpdateAnnouncements(ServiceReferenceMoto.AddOrUpdateAnnouncementsRequest request)
        {
            return base.Channel.AddOrUpdateAnnouncements(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.AddOrUpdateAnnouncementsResponse> AddOrUpdateAnnouncementsAsync(ServiceReferenceMoto.AddOrUpdateAnnouncementsRequest request)
        {
            return base.Channel.AddOrUpdateAnnouncementsAsync(request);
        }
        
        public ServiceReferenceMoto.GetAnnoucementSortByTitleResponse GetAnnoucementSortByTitle(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request)
        {
            return base.Channel.GetAnnoucementSortByTitle(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetAnnoucementSortByTitleResponse> GetAnnoucementSortByTitleAsync(ServiceReferenceMoto.GetAnnoucementSortByTitleRequest request)
        {
            return base.Channel.GetAnnoucementSortByTitleAsync(request);
        }
        
        public ServiceReferenceMoto.GetUsersResponse GetUsers(ServiceReferenceMoto.GetUsersRequest request)
        {
            return base.Channel.GetUsers(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetUsersResponse> GetUsersAsync(ServiceReferenceMoto.GetUsersRequest request)
        {
            return base.Channel.GetUsersAsync(request);
        }
        
        public ServiceReferenceMoto.GetUsersSortByUsernameResponse GetUsersSortByUsername(ServiceReferenceMoto.GetUsersSortByUsernameRequest request)
        {
            return base.Channel.GetUsersSortByUsername(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetUsersSortByUsernameResponse> GetUsersSortByUsernameAsync(ServiceReferenceMoto.GetUsersSortByUsernameRequest request)
        {
            return base.Channel.GetUsersSortByUsernameAsync(request);
        }
        
        public ServiceReferenceMoto.AddOrUpdateUserResponse AddOrUpdateUser(ServiceReferenceMoto.AddOrUpdateUserRequest request)
        {
            return base.Channel.AddOrUpdateUser(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.AddOrUpdateUserResponse> AddOrUpdateUserAsync(ServiceReferenceMoto.AddOrUpdateUserRequest request)
        {
            return base.Channel.AddOrUpdateUserAsync(request);
        }
        
        public ServiceReferenceMoto.GetBillsResponse GetBills(ServiceReferenceMoto.GetBillsRequest request)
        {
            return base.Channel.GetBills(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetBillsResponse> GetBillsAsync(ServiceReferenceMoto.GetBillsRequest request)
        {
            return base.Channel.GetBillsAsync(request);
        }
        
        public ServiceReferenceMoto.GetUserBillsResponse GetUserBills(ServiceReferenceMoto.GetUserBillsRequest request)
        {
            return base.Channel.GetUserBills(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetUserBillsResponse> GetUserBillsAsync(ServiceReferenceMoto.GetUserBillsRequest request)
        {
            return base.Channel.GetUserBillsAsync(request);
        }
        
        public ServiceReferenceMoto.GetUserMessagesResponse GetUserMessages(ServiceReferenceMoto.GetUserMessagesRequest request)
        {
            return base.Channel.GetUserMessages(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetUserMessagesResponse> GetUserMessagesAsync(ServiceReferenceMoto.GetUserMessagesRequest request)
        {
            return base.Channel.GetUserMessagesAsync(request);
        }
        
        public ServiceReferenceMoto.GetUserInAnnouncementMessagesResponse GetUserInAnnouncementMessages(ServiceReferenceMoto.GetUserInAnnouncementMessagesRequest request)
        {
            return base.Channel.GetUserInAnnouncementMessages(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetUserInAnnouncementMessagesResponse> GetUserInAnnouncementMessagesAsync(ServiceReferenceMoto.GetUserInAnnouncementMessagesRequest request)
        {
            return base.Channel.GetUserInAnnouncementMessagesAsync(request);
        }
        
        public ServiceReferenceMoto.GetBrandsResponse GetBrands(ServiceReferenceMoto.GetBrandsRequest request)
        {
            return base.Channel.GetBrands(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.GetBrandsResponse> GetBrandsAsync(ServiceReferenceMoto.GetBrandsRequest request)
        {
            return base.Channel.GetBrandsAsync(request);
        }
        
        public ServiceReferenceMoto.AddAnnouncementsResponse AddAnnouncements(ServiceReferenceMoto.AddAnnouncementsRequest request)
        {
            return base.Channel.AddAnnouncements(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.AddAnnouncementsResponse> AddAnnouncementsAsync(ServiceReferenceMoto.AddAnnouncementsRequest request)
        {
            return base.Channel.AddAnnouncementsAsync(request);
        }
        
        public ServiceReferenceMoto.AddBillResponse AddBill(ServiceReferenceMoto.AddBillRequest request)
        {
            return base.Channel.AddBill(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.AddBillResponse> AddBillAsync(ServiceReferenceMoto.AddBillRequest request)
        {
            return base.Channel.AddBillAsync(request);
        }
        
        public ServiceReferenceMoto.AddMsgResponse AddMsg(ServiceReferenceMoto.AddMsgRequest request)
        {
            return base.Channel.AddMsg(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceMoto.AddMsgResponse> AddMsgAsync(ServiceReferenceMoto.AddMsgRequest request)
        {
            return base.Channel.AddMsgAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMotoService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMotoService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:64946/MotoService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MotoServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMotoService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MotoServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMotoService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMotoService,
        }
    }
}
