//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMoto.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Announcements
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Announcements()
        {
            this.Bills = new HashSet<Bills>();
            this.Messages = new HashSet<Messages>();
        }
    
        public int IdAnnouncement { get; set; }
        public int IdUser { get; set; }
        public int IdBrand { get; set; }
        public int IdModel { get; set; }
        public int IdBodyType { get; set; }
        public int IdColor { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public bool Negotiable { get; set; }
        public Nullable<int> ProDate { get; set; }
        public Nullable<int> Mileage { get; set; }
        public Nullable<int> StrokeCapacity { get; set; }
        public Nullable<int> Power { get; set; }
        public bool IsActive { get; set; }
    
        public virtual BodyTypes BodyTypes { get; set; }
        public virtual Colors Colors { get; set; }
        public virtual Models Models { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bills> Bills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Messages> Messages { get; set; }
    }
}
