//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfMoto.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MotoEntities : DbContext
    {
        public MotoEntities()
            : base("name=MotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcements> Announcements { get; set; }
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<BodyTypes> BodyTypes { get; set; }
        public virtual DbSet<Brands> Brands { get; set; }
        public virtual DbSet<Colors> Colors { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Models> Models { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
